apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: microservice
spec:
  replicas : 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: gcr.io/google-samples/microservices-demo/adservice:v0.6.0
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  selector:
    app: adservice
  type: ClusterIP
  ports:
  - port: 9555
    targetPort: 9555

