apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: microservice
spec:
  replicas : 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: checkoutservice
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.6.0
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        - name: EMAIL_SERVICE_ADDR
          value: "emailservice:8080"
        - name: PAYMENT_SERVICE_ADDR
          value: "paymentservice:50051"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  selector:
    app: checkoutservice
  type: ClusterIP
  ports:
  - port: 5050
    targetPort: 5050

