apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: microservice
spec:
  replicas : 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.6.0
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  selector:
    app: currencyservice
  type: ClusterIP
  ports:
  - port: 7000
    targetPort: 7000

