apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: microservice
spec:
  replicas : 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.6.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe","-addr=:8080"]
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe","-addr=:8080"]
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"  
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  selector:
    app: emailservice
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080

