apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservice
spec:
  replicas : 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/google-samples/microservices-demo/frontend:v0.6.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice:8080"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice:5050"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: AD_SERVICE_ADDR
          value: "adservice:9555"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservice
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: microservice
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: frontend-tls-secret
#   namespace: microservice
# data: 
#   tls.crt: "dGxzLmNydA=="
#   tls.key: "dGxzLmtleQ=="
# type: kubernetes.io/tls
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: frontend-ingress
#   namespace: microservice
#   labels:
#     name: frontend-ingress
# spec:
#   tls:
#     - hosts:
#       - my-shop.com
#       secretName: board-tls-secret.default
#   rules:
#   - host: my-shop.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: /
#         backend:
#           service:
#             name: frontend
#             port: 
#               number: 80