apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: microservice
spec:
  replicas : 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.6.0
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: GRPC_HEALTH_PROBE_VERSION
          value: "0.4.18"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  selector:
    app: paymentservice
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051

