apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscart
  namespace: microservice
spec:
  replicas : 1
  selector:
    matchLabels:
      app: rediscart
  template:
    metadata:
      labels:
        app: rediscart
    spec:
      containers:
      - name: rediscart
        image: redis:alpine
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: rediscart
spec:
  selector:
    app: rediscart
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

