apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: microservice
spec:
  replicas : 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.6.0
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  selector:
    app: shippingservice
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051

